In [1]:
import pandas as pd

In [198]:
patient_df = pd.read_csv('patient_df_200508.csv')
patient_df = patient_df.drop('index', axis=1)
patient_df.head()

ds    y  14_ago  before_sum  before_mean  before_std  day_cat_d1  \
0  2020-01-20  1.0       0           0          0.0         0.0           1   
1  2020-01-24  1.0       0           0          0.0         0.0           1   
2  2020-01-26  1.0       0           0          0.0         0.0           1   
3  2020-01-27  1.0       0           0          0.0         0.0           1   
4  2020-01-30  1.0       0           0          0.0         0.0           1   

   day_cat_d2  day_cat_d3  day_cat_d4  day_cat_d5  day_cat_d6  day_cat_d7  \
0           0           0           0           0           0           0   
1           0           0           0           0           0           0   
2           0           0           0           0           0           0   
3           0           0           0           0           0           0   
4           0           0           0           0           0           0   

   day_cat_d8  
0           0  
1           0  
2           0  
3           0  
4           0

In [199]:
train_df = patient_df.iloc[:83]
test_df = patient_df.iloc[83:97]

X_train = train_df.drop(['ds', 'y'], axis=1, inplace=False)
X_test = test_df.drop(['ds', 'y'], axis=1, inplace=False)
y_train = train_df.y
y_test = test_df.y

# RandomForestRegressor

In [201]:
from sklearn.ensemble import RandomForestRegressor
rf_reg = RandomForestRegressor(random_state=2020)
rf_reg.fit(X_train, y_train)
preds = rf_reg.predict(X_test)

C:\Users\eh063\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [202]:
preds

array([8.44666667, 6.5       , 9.2       , 5.3       , 9.66666667,
       7.2       , 5.3       , 7.4       , 6.7       , 8.9       ,
       9.2       , 8.9       , 9.2       , 8.9       ])

In [203]:
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_test, preds)
rmse = np.sqrt(mse)
print(rmse)

3.512229880027606


In [204]:
y = round(y_test, 2)
y_hat = np.around(preds)

score = 100*(1-np.sum((y - y_hat)**2)/np.sum(y**2))
print(score)

74.39393939393939


## 2020-05-06~2020-05-19 예측

In [205]:
final = patient_df.iloc[97:]

In [206]:
X_test = final.drop(['ds', 'y'], axis=1, inplace=False)

In [207]:
preds = rf_reg.predict(X_test)
preds

array([8.3, 3.5, 3.5, 4.4, 4.4, 3. , 4.4, 3.5, 4.4, 4.4, 5.1, 4.4, 3.5,
       3.5])

## 2020-05-06~2020-05-10 예측값으로 모델의 정확도 확인

In [208]:
preds[:5]

array([8.3, 3.5, 3.5, 4.4, 4.4])

In [209]:
# 2020-05-06~2020-05-10 예측값
yhat=preds[:5]
# 2020-05-06~2020-05-10 실젝 해외 유입 환자수
y=[2,3,11,1,8]

a=[]
b=[]
for i in range(len(y)):
    a.append((y[i]-yhat[i])**2)
for i in range(len(y)):
    b.append(y[i]**2)
100*(1-np.sum(a)/np.sum(b))   

39.34170854271356

5월 6일부터 5월 10일까지의 확진자 수를 가지고 모델의 정확도를 계산한 결과 성능이 좋지 않음.  
오버피팅이 심한 모델이라 생각되어 RandomForest Regressor을 모델로 